In [1]:
import numpy as np


def val(w, x):
    sum = 0
    for i in range(x.shape[0]):
        sum += w[i] * x[i]
    if sum >= 0:
        return 1
    else:
        return -1


def Perceptron(x, y, w):
    wOld = w
    wNew = 0
    n = 1
    itr = 100
    for i in range(itr):
        sum = np.zeros(x.shape[1])
        for j in range(x.shape[0]):
            if y[j] * val(wOld, x[j]) < 0:
                sum += x[j] * y[j]
                # print(sum)
        wNew = wOld + n * sum
        # Convergence Criteria is satisfied or no of iteration < itr
        if np.array_equal(wOld, wNew):
            break
        wOld = wNew
        print(wNew)
    print('Final Value of W')
    print(wNew)


x = np.array([[1, 1, 1],
              [-1, -1, 1],
              [2, 2, 1],
              [-2, -2, 1],
              [-1, 1, 1],
              [1, -1, 1]])
y = np.array([[-1],
              [-1],
              [1],
              [-1],
              [1],
              [1]])
wOld = [0, 1, -1]
Perceptron(x, y, wOld)
# For the 1st Question it converges
# For 2nd Question it oscillates

[ 0. -1. -1.]
[ 4.  5. -1.]
[ 4.  3. -1.]
[ 2.  3. -1.]
[ 2.  1. -1.]
[ 0.  1. -1.]
[ 0. -1. -1.]
[ 4.  5. -1.]
[ 4.  3. -1.]
[ 2.  3. -1.]
[ 2.  1. -1.]
[ 0.  1. -1.]
[ 0. -1. -1.]
[ 4.  5. -1.]
[ 4.  3. -1.]
[ 2.  3. -1.]
[ 2.  1. -1.]
[ 0.  1. -1.]
[ 0. -1. -1.]
[ 4.  5. -1.]
[ 4.  3. -1.]
[ 2.  3. -1.]
[ 2.  1. -1.]
[ 0.  1. -1.]
[ 0. -1. -1.]
[ 4.  5. -1.]
[ 4.  3. -1.]
[ 2.  3. -1.]
[ 2.  1. -1.]
[ 0.  1. -1.]
[ 0. -1. -1.]
[ 4.  5. -1.]
[ 4.  3. -1.]
[ 2.  3. -1.]
[ 2.  1. -1.]
[ 0.  1. -1.]
[ 0. -1. -1.]
[ 4.  5. -1.]
[ 4.  3. -1.]
[ 2.  3. -1.]
[ 2.  1. -1.]
[ 0.  1. -1.]
[ 0. -1. -1.]
[ 4.  5. -1.]
[ 4.  3. -1.]
[ 2.  3. -1.]
[ 2.  1. -1.]
[ 0.  1. -1.]
[ 0. -1. -1.]
[ 4.  5. -1.]
[ 4.  3. -1.]
[ 2.  3. -1.]
[ 2.  1. -1.]
[ 0.  1. -1.]
[ 0. -1. -1.]
[ 4.  5. -1.]
[ 4.  3. -1.]
[ 2.  3. -1.]
[ 2.  1. -1.]
[ 0.  1. -1.]
[ 0. -1. -1.]
[ 4.  5. -1.]
[ 4.  3. -1.]
[ 2.  3. -1.]
[ 2.  1. -1.]
[ 0.  1. -1.]
[ 0. -1. -1.]
[ 4.  5. -1.]
[ 4.  3. -1.]
[ 2.  3. -1.]
[ 2.  1. -1.]
[ 0.  

In [3]:
import numpy as np
import pandas as pd


def cost(x, w, y):
    err = np.dot(x, w) - y
    j = np.sum(err ** 2)*(1/x.shape[0])
    return j


def gradient_descent(x, y, n):
    wOld = np.random.random_integers(0, 10, (x.shape[1], 1))
    itr = 1000
    c = 0
    while (c < itr):
        sum = np.dot((np.dot(x, wOld) - y).T, x)
        sum = sum.T
        wNew = wOld - n * (1 / x.shape[0]) * sum
        c += 1
        if np.array_equal(wOld, wNew):
            break
        wOld = wNew
        err = cost(x, wNew, y)
        print(err)
    print("no of steps: ",c)


data = np.array(pd.read_csv("wine.data"))
x = data[:, 0:13]
y = data[:, 13:14]
gradient_descent(x, y, 0.01)


# calculating optimal leaning rate
wOld = np.random.random_integers(0, 10, (x.shape[1], 1))
delJ = np.dot(wOld.T,wOld)
hessian = np.dot(x.T, x)
a = np.dot(wOld.T,hessian)
a = np.dot(a,wOld)
n = delJ[0, 0]/a[0, 0]
print('Gradient descent using optimal learning Rate')
gradient_descent(x, y, n)
print(n)

c:\users\pc\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:12: DeprecationWarning: This function is deprecated. Please call randint(0, 10 + 1) instead
  if sys.path[0] == '':
c:\users\pc\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: overflow encountered in square
  import sys
c:\users\pc\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:18: RuntimeWarning: invalid value encountered in subtract
c:\users\pc\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:35: DeprecationWarning: This function is deprecated. Please call randint(0, 10 + 1) instead


355105767.3019044
4001595884719.0083
4.510302090282162e+16
5.083678087951514e+20
5.729944998061256e+24
6.458369139977761e+28
7.279394821822889e+32
8.204794093290931e+36
9.247835535927693e+40
1.042347451101775e+45
1.1748567592896496e+49
1.3242114262279765e+53
1.4925529325063988e+57
1.682294996259854e+61
1.8961581815985675e+65
2.1372089066642045e+69
2.4089034106184193e+73
2.7151373099722826e+77
3.0603014548063473e+81
3.4493448857602894e+85
3.887845794483532e+89
4.382091504993595e+93
4.939168622732877e+97
5.567064643901048e+101
6.274782481960473e+105
7.07246955342124e+109
7.971563273766639e+113
8.984955049672235e+117
1.0127175118875408e+122
1.14146008879711e+126
1.286569175532724e+130
1.450125378606356e+134
1.63447380340626e+138
1.8422576788420715e+142
2.0764562565515757e+146
2.3404275280764358e+150
2.637956372495307e+154
2.973308824865832e+158
3.351293243588613e+162
3.777329253724417e+166
4.2575254547893975e+170
4.798767007220006e+174
5.4088143533418724e+178
6.096414488326041e+182
6.8714

82230.13191942262
82228.08063695481
82226.02952664207
82223.97858846773
82221.92782241512
82219.87722846761
82217.8268066085
82215.77655682118
82213.72647908892
82211.67657339512
82209.62683972312
82207.57727805625
82205.52788837787
82203.47867067133
82201.42962491997
82199.3807511072
82197.33204921627
82195.28351923065
82193.23516113362
82191.18697490859
82189.1389605389
82187.09111800793
82185.04344729902
82182.99594839556
82180.94862128088
82178.90146593843
82176.8544823515
82174.8076705035
82172.76103037782
82170.71456195784
82168.66826522686
82166.62214016839
82164.57618676573
82162.53040500225
82160.48479486138
82158.43935632649
82156.39408938096
82154.34899400822
82152.30407019163
82150.25931791458
82148.21473716048
82146.17032791273
82144.12609015468
82142.0820238698
82140.03812904148
82137.99440565311
82135.95085368805
82133.9074731298
82131.86426396169
82129.82122616719
82127.77835972965
82125.73566463254
82123.69314085924
82121.65078839316
82119.60860721777
82117.56659731646